[package]
name = "test_vector"
version = "1.0.0"
authors = []

[addresses]
test = "0xc78884f19e8868fb55fa82a0cff968bcd755d00f55e79f52d375b9fcccc61f58"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
